In [7]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [8]:
#x'=x-min/(max-min)  X''=X'*(max-min)+min
mm=MinMaxScaler(feature_range=(0,1))  # range
data=[[90,2,10,40],[60,5,15,45],[73,3,13,45]]
data=mm.fit_transform(data)
print(data.mean())
print(data)

0.5305555555555556
[[1.         0.         0.         0.        ]
 [0.         1.         1.         1.        ]
 [0.43333333 0.33333333 0.6        1.        ]]


In [9]:
stand=StandardScaler()
data=[[90,2,10,40],[60,5,15,45],[73,3,13,45]]
data=stand.fit_transform(data)
print(data)
print(data.mean())

[[ 1.27540458 -1.06904497 -1.29777137 -1.41421356]
 [-1.16685951  1.33630621  1.13554995  0.70710678]
 [-0.10854507 -0.26726124  0.16222142  0.70710678]]
-1.4802973661668753e-16


In [10]:
from sklearn.feature_selection import VarianceThreshold
v=VarianceThreshold(threshold=3)
data=v.fit_transform([[0,2,4,3],[0,3,7,3],[0,9,6,3]])
print(data.mean())
data

4.666666666666667


array([[2],
       [3],
       [9]])

In [11]:
import numpy as pd
featrue=pd.random.randint(0,100,size=(5,10))
featrue

array([[12,  4, 89, 31, 88,  3, 56, 33, 12, 70],
       [67, 95, 56,  8, 58, 58,  0, 48, 51, 71],
       [43, 34, 82, 67, 92, 62, 62, 86,  4, 56],
       [31, 74, 18,  8, 16,  7,  8, 71, 74, 83],
       [52, 23, 80, 90,  2, 26, 79, 51, 41, 71]])

In [12]:
med=np.median(featrue.var(axis=0))

In [13]:
v=VarianceThreshold(threshold=med)
v.fit_transform(featrue)

array([[ 4, 89, 31, 88, 56],
       [95, 56,  8, 58,  0],
       [34, 82, 67, 92, 62],
       [74, 18,  8, 16,  8],
       [23, 80, 90,  2, 79]])

In [14]:
from sklearn.decomposition import PCA
pca=PCA(n_components=3)
pca.fit_transform([[0,2,4,3],[0,3,7,3],[0,9,6,3]])

array([[-2.88362421e+00, -1.25443227e+00,  8.61572474e-17],
       [-1.45140588e+00,  1.56492061e+00,  8.61572474e-17],
       [ 4.33503009e+00, -3.10488337e-01,  8.61572474e-17]])

In [15]:
from sklearn.model_selection import train_test_split
import sklearn.datasets as ds
iris=ds.load_iris()

In [16]:
feature=iris['data']
target=iris.target
feature.shape

(150, 4)

In [22]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
#get large datasets
# news_data=ds.fetch_20newsgroups(data_home=None,subset="all",random_state=22)
# news_data

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(feature,target,test_size=0.5,random_state=22)

In [33]:
x_test.shape

(75, 4)